### ISSUE TITLE
[BUG] Planetary info not appearing when landing

### ISSUE THREAD

**Issue by Koishukaze** [EladNLG/EladsHUD#14]
Without EladsHUD ![image](https://github.com/EladNLG/EladsHUD/assets/47912135/a311c04e-321e-4043-860b-87a1e146abad)
With EladsHUD ![image](https://github.com/EladNLG/EladsHUD/assets/47912135/4677b096-09c3-463f-ae4e-25379b802526)

Also tested on a profile with just EladsHUD, same issue

**Comment by N0aW** [comment]
Isn't this a duplicate of #2?

**Comment by EladNLG** [comment]
I CAN CLOSE THIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIS AFTER SOOOOOOOOOOOOOOOO LONGGGGGGGGGGGGG

Fixed in 1.3
