### ISSUE TITLE
Hazard Level not appearing

### ISSUE THREAD

**Issue by THomasHfds2** [EladNLG/EladsHUD#2]
I noticed that every time I load into a moon with this mod enabled the light blue text that appears as you land the ship doesn't show up. It normally states the moon name, moon description, and the hazard level, but for some reason they don't appear.

**Comment by bluehead24** [comment]
same here

**Comment by EladNLG** [comment]
I CAN CLOSE THIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIS AFTER SOOOOOOOOOOOOOOOO LONGGGGGGGGGGGGG

Fixed in 1.3
