### ISSUE TITLE
Missing files of asserts

### ISSUE THREAD

**Issue by BoredBean** [EladNLG/EladsHUD#8]
I’m attempting to compile this plugin on my own, but I’m unable to locate a certain asset:
`  <ItemGroup>
    <EmbeddedResource Include="C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\asset_export\Lethal Company\lethal modding\Assets\AssetBundles\customhud" />
  </ItemGroup>`
If you’re not willing to open-source this asset, could you please guide me on how to create one myself? I’ve just learned how to create a UI in Unity, but I’m uncertain about how to export them."

**Comment by EladNLG** [comment]
Hi, I did not expect anyone to actually try to compile the plugin themselves, so i didnt bother releasing the assets. I'll work on open-sourcing the Unity project soon.

**Comment by BoredBean** [comment]
I'm currently creating another mod without any knowledge of C# or Unity. 
I just realized that this HUD is the best example for me to learn about UI replacement. 
Now I have the clue. 
I love this mod btw. 
Thank you for your work!

**Comment by EladNLG** [comment]
Hey, please dont close the issue or i might forget lol

**Comment by EladNLG** [comment]
Can actually be closed now lol
