### ISSUE TITLE
Oxygen level Enhancement

### ISSUE THREAD

**Issue by Sourceshard** [EladNLG/EladsHUD#9]
I would love to see an optional Oxygen Level bar that fits with your hud design.

https://thunderstore.io/c/lethal-company/p/consequential/Oxygen/

**Comment by execOQ** [comment]
@Sourceshard, hey! I just released an update that provides support for EladesHUD!

**Comment by Sourceshard** [comment]
@execOQ  Ohh very excited to try this out! Thank you very much!

**Comment by EladNLG** [comment]
@execOQ thanks a lot (i dont really play lethal company much anymore so development of the mod has grinded to a halt... ;-;)

Can i consider this closed?

**Comment by Sourceshard** [comment]
Yes this has been solved.

**Comment by execOQ** [comment]
> @execOQ thanks a lot (i dont really play lethal company much anymore so development of the mod has grinded to a halt... ;-;)
> 
> Can i consider this closed?

yep, the hype around LC is going a little down)
